# app-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-microservice-deployment
  namespace: tu_namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-microservice
  template:
    metadata:
      labels:
        app: nodejs-microservice
    spec:
      containers:
      - name: nodejs-microservice-container
        image: tu_usuario_dockerhub/nombre_de_tu_imagen:1.0  # Especifica la versi√≥n correcta
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: nodejs-microservice-service
  namespace: tu_namespace
spec:
  selector:
    app: nodejs-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
